### ISSUE TITLE
Make the scheduler stateless

### ISSUE THREAD

**Issue by zpatrick** [quintilesims/layer0#104]
The scheduler is currently a stateful component of the api. This has led to bugs with users who scale the api > 1. We need to update this component to make the api a stateless service. 

The "scheduler" is a relatively high-level concept - more concretely, it's the relationship between the the cluster scalar, task scheduler, and right sizer. Luckily, we can use many existing components to make the scheduler stateless. 

I think the following architecture changes can provide us with a stateless scheduler with the minimum amount of refactoring:

## Tasks 
Remove the task scheduler and run tasks as jobs. In the same way the ecs service scheduler works, the "Run Task" job would simply try and retry running the task until there is adequate resources in the environment. 

## Scalar
This would be a combination of the right sizer (which scales clusters down) and the cluster scalar (which scales clusters up). Simply put, the scalar runs a single, stateless function that is very similar to `OptimizeCluster` in the current right sizer:
* Gather the resources in the environment - the number of **desired** (not current!) instances in the autoscaling group. 
* Gather the required resources in the environment - the number of running services and tasks + the number of pending services and tasks.
* Make logical decisions on whether to scale the autoscaling group up, down, or do nothing. 
* We would need a simple locking mechanism to enforce that the Scalar function never runs in parallel.

**Comment by diemonster** [comment]
Regarding schedule improvements, would it be worth investigating this first? https://blox.github.io/
