### ISSUE TITLE
Clean L0 removal to remove API as well as child resources

### ISSUE THREAD

**Issue by tribaljack** [quintilesims/layer0#109]
When destroying a L0 instal with `l0-setup destroy`, we should free up all resources allocated by that L0-API.  Need to figure in failures at varying stages including:
* L0 API non-responsive
* idempotent destroy
* child resources (LB/Task/Services) non-responsive or in flux

**Comment by diemonster** [comment]
We already provide documentation on how to properly `destroy` a Layer0 instance via http://layer0.ims.io/setup/destroy/
