### ISSUE TITLE
Update Layer0 examples to include user guide code

### ISSUE THREAD

**Issue by diemonster** [quintilesims/layer0#112]
https://github.com/quintilesims/layer0-examples currently lacks many of the examples described in our User's Guide. We specifically need:

- One-off tasks
- Guestbook w Consul
- Guestbook w RDS (this may need to be adapted to Guestbook w Dynamo instead?)

**Comment by tlake** [comment]
I'm currently working on the documentation side of things in [this branch](https://github.com/quintilesims/layer0/tree/documentation-guides);
- updating the guestbook guide
- replacing rds-guestbook with more general stateless-guestbook-with-external-db, referencing the dynamo-guestbook example
- marking the consul guides as "under construction" until we actually have the right content and matching resources

**Comment by tlake** [comment]
Closing this issue as it's no longer accurate. See issue #169.
