### ISSUE TITLE
Migrate Layer0 Binaries to Github

### ISSUE THREAD

**Issue by diemonster** [quintilesims/layer0#117]
We currently host released binaries in S3, but that isn't necessary with Github. Let's do the following:

- migrate our older releases (just v0.8.4+) to Github
- update the release script to push binaries to Github.

https://help.github.com/articles/creating-releases/

**Comment by tlake** [comment]
We should also figure out a good solution to creating binaries/releases and pushing tags that allows for some good automation. As a minor example, needing to manually update version numbers for the badges in the README is annoying and liable to be forgotten.

Related to #183.
