### ISSUE TITLE
Loadbalancer help is misleading

### ISSUE THREAD

**Issue by diemonster** [quintilesims/layer0#125]
```
NAME:
   l0 loadbalancer create - create a new load balancer

USAGE:
   l0 loadbalancer create [command options] ENVIRONMENT NAME

OPTIONS:
   --port value                             port configuration in format 'HOST_PORT:CONTAINER_PORT/PROTOCOL' (default 80:80/tcp)
[clipped]
```

The problem here is that the CLI's help (as well as our docs site) refer to HOST PORT and CONTAINER PORT when they should be referring to LB_PORT and HOST PORT, respectively. An ELB has no knowledge of the Host Port to Container port mapping.

**Comment by tlake** [comment]
I assume that we'll also want to update all the internals to reflect this as well?


```
type Port struct {
	CertificateName string `json:"certificate_name"`
	ContainerPort   int64  `json:"container_port"`
	HostPort        int64  `json:"host_port"`
	Protocol        string `json:"protocol"`
}
```
should become
```
type Port struct {
	CertificateName string `json:"certificate_name"`
	HostPort   int64  `json:"host_port"`
	LBPort        int64  `json:"lb_port"`
	Protocol        string `json:"protocol"`
}
```
and all the ripples that entails?

**Comment by zpatrick** [comment]
sounds good to me. note that this will need to be in v.10 since its a breaking api change

**Comment by tlake** [comment]
It seems like we've decided to dismiss this change and continue with the verbage that we already have? Marking this closed unless we change our minds.
