### ISSUE TITLE
Documentation has too many slashes in links http://docs.xfra.ims.io/

### ISSUE THREAD

**Issue by Cryowatt** [quintilesims/layer0#129]
The documentation contains links like `https://github.com/quintilesims/layer0//archive/v0.8.4.zip` and `https://github.com/quintilesims/layer0//stargazers` that have double `/` characters.

**Comment by diemonster** [comment]
http://docs.xfra.ims.io is deprecated; the new docs reside at https://quintilesims.github.io/layer0/
