### ISSUE TITLE
Layer0 doesn't follow conventions for user data storage

### ISSUE THREAD

**Issue by Cryowatt** [quintilesims/layer0#130]
Most applications, when storing data in the user folder on a system, will prefix the folder name with `.`. For example, docker uses `~/.docker`, vscode uses `~/.vscode`, aws uses `~/.aws`, etc. Layer0 should follow this convention as well.

On windows, the behavior is the same, but the more platform-accepted way is to store user data under $APPDATA (C:\Users\username\AppData\Roaming) or $ProgramData (c:\ProgramData) for global settings.

**Comment by diemonster** [comment]
Agreed with the first point in terms of convention, although changing it would force us to support both folder paths unless we were OK with breaking changes. I would suggest pushing this fix to our next major version so we can make a clean break.

@Cryowatt you mention global settings for Windows, but in the first case, we're talking about user settings specifically, hence `~`. What's the best way to store settings per user?

**Comment by Cryowatt** [comment]
$APPDATA or ~/.layer0 would be fine for user-specific data. All the examples I gave above are from my Windows box.

**Comment by diemonster** [comment]
`$APPDATA` and `~/.layer0` sounds good, we'll look at prioritizing this. Thanks!
