### ISSUE TITLE
l0-setup destroy myenv should delete ~/layer0/instances/myenv

### ISSUE THREAD

**Issue by Cryowatt** [quintilesims/layer0#134]
Seems like these files should be removed if I've destroyed the environment.

**Comment by diemonster** [comment]
@Cryowatt `l0-setup destroy` is about destroying AWS resources, but not removing all traces of that instance from your local machine. There are cases where you need to `destroy` and `apply` again, so I don't think deleting the files locally would be something we'd want to do.

We could add a `l0-setup` command that purged stale instances from `~/layer0/instances` but I don't believe that's a priority at this moment.

**Comment by Cryowatt** [comment]
I think what I'm looking for here is a workflow like this:.

```
>l0-setup ls

Environment Status
----------- ------
myenv       Up

>l0-setup rm myenv

Error: Environment still running, bring it down first.

>l0-setup down myenv

Brining down environment...
/* terraform here */

>l0-setup ls

Environment Status
----------- ------
myenv       Down

>l0-setup rm myenv

Removed environment

>l0-setup ls

<no environments found>
```
