### ISSUE TITLE
Migrate from a MySQL instance to dynamodb or equivalent

### ISSUE THREAD

**Issue by Cryowatt** [quintilesims/layer0#136]
It looks like the MySQL instance is only storing two tables that are flat and do not contain foreign key references.
https://github.com/quintilesims/layer0/blob/29391fe9bf9c7e9a0503a3de5edaa9342a86bc56/common/db/scripts.go

Instead of running a MySQL instance which charges by the hour, why not move to something like dynamo where the charges are per-transaction? Seems like this would be a huge savings cost.

**Comment by zpatrick** [comment]
related to https://github.com/quintilesims/layer0/issues/37

**Comment by zpatrick** [comment]
closed by https://github.com/quintilesims/layer0/pull/206
