### ISSUE TITLE
Layer0 Right Sizer recreates instance(s) when ECS Agent is in disconnected state

### ISSUE THREAD

**Issue by diemonster** [quintilesims/layer0#14]
The problem: 

Complex applications that can be deployed within Layer0 are not always able to withstand automatic service restarts and/or Layer0 Right Sizer instance terminations. 

Currently, we're optimized for use cases that fit cleanly into the Docker paradigm, where all services that comprise an application are disposable and scalable. However, some services like Splunk don't fit so cleanly into this model, yet still benefit from using the Docker workflow. 

For example, with Splunk, we've seen cases where the Splunk Master instance (which is not a scalable service) is forced to terminate because the ECS Agent is listed as "disconnected". When a new Splunk Master container is eventually brought back online, it is unable to reconcile with the remaining Splunk services. 

The Right Sizer code that controls this behavior:
https://github.com/quintilesims/layer0/blob/master/api/backend/ecs/right_sizer.go#L119

The solution(s):

- Disallow services like Splunk on Layer0 😭 
- Create a param or flag that allows the user to control the Right Sizer's scaling behavior. In this case, change the behavior when the ECS Agent is "disconnected" to log a WARN event, but not actually terminate the instance.
- ??? any other ideas?

**Comment by zpatrick** [comment]
In addition - the Right Sizer should check if the ecs agent connection is flapping before terminating the instance. Right now, we terminate the instance if the ecs agent becomes disconnected at any point. 
Since the Right Sizer runs once per hour, I'd suggest we only terminate the instance if the agent reports disconnected ~3 times in a row.

**Comment by zpatrick** [comment]
I think adding a configuration variable like `LAYER0_TERMINATE_ON_DISCONNECT` (default = `true`) is our best option. If users don't want this option, they can change the corresponding variable in `terraform.tfvars` from `true` to `false` and run `l0-setup apply`.

**Comment by diemonster** [comment]
After some more consideration, the premise of "solving" this issue by making the scheduler more permissive is at odds with a critical pattern we've adopted in Layer0, namely the Pets vs Cattle service analogy. If a service cannot withstand being autoscaled up or down, then Layer0 is not the right tool for the job.
