### ISSUE TITLE
Loadbalancer healthcheck params are confusing

### ISSUE THREAD

**Issue by diemonster** [quintilesims/layer0#142]
Our current CLI impl of loadbalancer healthchecks are proving confusing for users -- @Cryowatt, @andycmaj, and @sesh-kebab have all missed our docs and/or have gotten bit by the 'new' behavior, which suggests it needs some refinement.

A suggested approach:

- We revert to the old `loadbalancer` healthcheck behavior of picking a supplied port from `--port` and use that for the default healthcheck. We then warn the user that a default has been picked automatically.

**Comment by Cryowatt** [comment]
It doesn't help that the help output of l0 doesn't match the documentation provided on https://quintilesims.github.io/layer0/

Most of the guides specify instructions like `l0 loadbalancer create --private --port 8500:8500/tcp demo consullb` which results in an incorrectly configured health check.

I'm fine with either warning the users, or requiring user action if the healthcheck port to use is ambiguous.

**Comment by tlake** [comment]
Is the confusion that configuring a loadbalancer's ports and configuring the healthcheck target are two different things? Are folks thinking that the `--ports` flag has some relationship to the healthcheck configuration?

**Comment by sesh-kebab** [comment]
Speaking for myself I prefer the new behavior. I think the user should be made aware of and should be forced to choose a port that would most accurately represent the health of the service that they're deploying.

A warning can and probably would be ignored too easily. What caught me off guard was not being aware of the healthcheck target change when switching to the new version.

**Comment by zpatrick** [comment]
In regards to @Cryowatt's comment, it sounds like we need documentation updates in all the guides.

**Comment by diemonster** [comment]
OK, forget my suggestion then 😆. Let's update the docs accordingly.

Going forward, I think we need to remember that CLI changes need _all_ doc updates to be made in tandem.
