### ISSUE TITLE
Make Consul a Layer1 Service

### ISSUE THREAD

**Issue by tlake** [quintilesims/layer0#144]
Currently a WIP, but our Consul service needs to be fully migrated to GitHub, with all the documentation updates and fixes and changes that entails. Additionally, it's going to be set up for use with Terraform.

**Comment by diemonster** [comment]
https://github.com/quintilesims/consul is no longer WIP

**Comment by zpatrick** [comment]
@bivers: what about making this consumable as a terraform module?

**Comment by diemonster** [comment]
will address terraform module in this feature https://github.com/quintilesims/layer0/issues/163
