### ISSUE TITLE
automate windows environment creation in Layer0 -- API

### ISSUE THREAD

**Issue by tribaljack** [quintilesims/layer0#152]
Semantic:
> l0 environment create --os=windows <env name>

Do we need to worry about minimum ec2 instance type for windows? given the larger base image?

**Comment by andycmaj** [comment]
so here's the part in userdata.ps1 that ended up working for private docker auth:

```
...

# Configure docker auth
# TODO: temporary hack
$dockercfgContent = '{"d.ims.io":{"auth":"<***PRIVATE_REG_AUTH_TOKEN***>","email":""}}';
[Environment]::SetEnvironmentVariable("ECS_ENGINE_AUTH_DATA", $dockercfgContent, "Machine")
[Environment]::SetEnvironmentVariable("ECS_ENGINE_AUTH_TYPE", "dockercfg", "Machine")

# Output all environment variables
Get-ChildItem -Path Env:* | Sort-Object Name

...
```

Few notes about the actual solution:

* AWS Powershell tools are already installed on the AMI, so you can do `Copy-S3Object -BucketName "{{ .S3Bucket }}" -Key "bootstrap/dockercfg" -LocalFile "dockercfg"`

**Comment by diemonster** [comment]
@andycmaj nice! I'll add this to the hacky instructions for now. thanks!
