### ISSUE TITLE
Improve in-tool documentation

### ISSUE THREAD

**Issue by ignatzami** [quintilesims/layer0#161]
When I type in an incorrect command and "Error: incorrect usage" is all I get back, and the corresponding web docks don't offer any more help, I'm not going to use your tool.

Provide at the bare minimum:
1) A man page with examples baked into the tool
2) Meaningful error messages, with a level of verbosity that I can actually move forward. See Git, they do an amazing job of this.
3) Online documentation that doesn't suck. Examples, walkthroughs, tutorials, anything.

**Comment by tribaljack** [comment]
Known issue.

**Comment by tribaljack** [comment]
CLI usage has help in the form of adding '-h' to command.  such as:

> l0 -h
> l0 environment -h
> l0 environment create -h
