### ISSUE TITLE
Support IAM Roles/Key discovery

### ISSUE THREAD

**Issue by ignatzami** [quintilesims/layer0#162]
AWS supports a number of ways for a local machine to cache and manage AWS permissions, via keys, or an IAM role.

Most sensible organizations do not provide secret/access keys to their devs as it's a massive security flaw. Support local IAM roles via the AWS CLI. Please.

**Comment by diemonster** [comment]
Secret access keys can already be created via IAM for use with Layer0, and these keys can be as restricted as required by an org. Closing because this functionality already exists.
