### ISSUE TITLE
Enable Consul deployment via Terraform / Layer0 module

### ISSUE THREAD

**Issue by diemonster** [quintilesims/layer0#163]
[Consul](https://github.com/quintilesims/consul) is currently deployed using a task definition and a series of manual steps with `l0`. Let's add a terraform configuration that removes the manual steps.

Potential tricky parts include 'waiting for the service scale to reach a certain level' and/or anything that requires dependencies. There are some good ideas in the terraform community on how we might get around that:
https://github.com/hashicorp/terraform/issues/1007

i.e. 
```
provisioner "local-exec" {
    command = "l0 service scale <name> 1"
}
```

**Comment by zpatrick** [comment]
closed by https://github.com/quintilesims/consul/pull/1
