### ISSUE TITLE
Default VPC Template should enable private DNS

### ISSUE THREAD

**Issue by ignatzami** [quintilesims/layer0#165]
Current:
DNS resolution: yes
DNS hostnames: no

This should be yes, for both, to allow for private R53 zones.

**Comment by shayankay** [comment]
what's the need for R53?

**Comment by tribaljack** [comment]
L0 creates a new SG for each port set that is allocated by a service's ELB, just like the EC-EC, RDS to RDS mapping that we've used.  That model seems to work fine without the need to collapse SGs.  AWS limit on SG is 500 per VPS per region, with option to increase SG as needed here: https://console.aws.amazon.com/support/home#/case/create?issueType=service-limit-increase&limitType=service-code-vpc

No need to fix this now.
