### ISSUE TITLE
Guide: Terraform Beyond Layer0

### ISSUE THREAD

**Issue by tlake** [quintilesims/layer0#173]
This guide is not part of the walkthrough; it is instead a stand-alone guide meant to illustrate how a person might go about incorporating usage of our layer0-terraform-provider into a Terraform workflow that also uses other providers. This guide is meant to make use of the [layer0-examples](https://github.com/quintilesims/layer0-examples/)/guestbook-db repo, which configures a DynamoDB instance using an AWS provider, as well as our guestbook app using the Layer0 provider.

This guide doesn't have a Layer0 CLI analogue.

It should be relatively simple - just a migration of the material in the Guestbook With A DB guide over in the `documentation-guides` branch.

- [ ] Deploy with Terraform
- [ ] Make sure the [layer0-examples](https://github.com/quintilesims/layer0-examples/)/guestbook-db repo is aligned

**Comment by sesh-kebab** [comment]
First iteration closed by #184
