### ISSUE TITLE
Unable to Find or Delete Phantom Service

### ISSUE THREAD

**Issue by tlake** [quintilesims/layer0#196]
# Summary
My Layer0 CLI reports the existence of a service seemingly nonexistent everywhere else, and it can't be deleted.

# Description
The phantom service shares a name (`guestbook-svc`) with another service, so trying to access the real service requires me to use the ID. Running `l0 service list` does **not** display the phantom service, but `get` does:
```
$ l0 service list

SERVICE ID    SERVICE NAME   ENVIRONMENT
redissv0976a  redis-svc      demo-env
guestbo5fadd  guestbook-svc  demo-env
api           api            api

$ l0 service get guestbook-svc

SERVICE ID    SERVICE NAME   ENVIRONMENT   LOADBALANCER  DEPLOYMENTS      SCALE
guestbo9364b  guestbook-svc  demoenv30869  guestbodb65a  guestbook-dep:1  0/0
guestbo5fadd  guestbook-svc  demo-env      guestbook-lb  guestbook-dpl:7  1/1
```
_(ID=`guestbo9364b` is the phantom service; ID=`guestbo5fadd` is the real one.)_

This environment (and all the stuff in it) has been deleted already, and everything except the Layer0 CLI seems to reflect that reality; there is no `demoenv*` cluster in ECS, these resources don't show up in the tag database of the API, nor have I been able to retrieve them through the AWS CLI.

# Repro
Unfortunately, I have no idea how this error came to be. :| It seems to be a relic from some previous environment, but my API and CLI versions haven't changed, so I think we can rule out weird update artifacts.

# Other Thoughts
If nothing else, this seems to be a discovery of a new error that we haven't accounted for. In checking the logs for the `service delete` job, the following is reported until the job fails:
```
$ l0 job logs 05a3c09eaae1

l0-job
------
2017-04-05 23:44:04 [Main] INFO : Loading job '05a3c09eaae1'
2017-04-05 23:44:04 [Main] INFO : Running step 'Delete Service'
2017-04-05 23:44:04 [Main] INFO : Running Action: DeleteService on 'guestbo9364b'
2017-04-05 23:44:04 [Main] WARN : ServiceNotActiveException: Service was not ACTIVE.
        status code: 400, request id: c0ef2919-1a59-11e7-8497-2d70ed92b85c
2017-04-05 23:44:14 [Main] INFO : Running Action: DeleteService on 'guestbo9364b'
2017-04-05 23:44:15 [Main] WARN : ServiceNotActiveException: Service was not ACTIVE.
        status code: 400, request id: c702a4c5-1a59-11e7-8497-2d70ed92b85c
2017-04-05 23:44:25 [Main] INFO : Running Action: DeleteService on 'guestbo9364b'
2017-04-05 23:44:25 [Main] WARN : ServiceNotActiveException: Service was not ACTIVE.
        status code: 400, request id: cd0b4a76-1a59-11e7-8497-2d70ed92b85c
. . .
. . .
. . . 
```
We should probably look into handling that `ServiceNotActiveException` warning.

**Comment by diemonster** [comment]
Unable to reproduce
