### ISSUE TITLE
Set "binpack" placement strategy as default

### ISSUE THREAD

**Issue by zpatrick** [quintilesims/layer0#197]
By default, we should render deploys with the "binpack" strategy if one isn't already set (similar to how we render logging). Docs here: http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-placement-strategies.html

**Comment by diemonster** [comment]
What is the current default strategy if the param isn't set? I'm not seeing any indicate of what that would be from the ECS docs.

**Comment by zpatrick** [comment]
described here: http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-placement.html
