### ISSUE TITLE
Validate `l0-setup` configuration variables prior to provisioning

### ISSUE THREAD

**Issue by diemonster** [quintilesims/layer0#228]
Also related to https://github.com/quintilesims/layer0/issues/133

`l0-setup` currently asks the user for the following configuration, which is _not_ currently validated:
- AWS access keys
- AWS EC2 keypair
- `config.json` or `.dockercfg` 

All these things should be validated prior to running `terraform`, as they can cause the user significant headache otherwise. In the later example, incorrect docker repository config will blast whatever docker repo is configured with potentially bad login attempts continually.

**Comment by zpatrick** [comment]
Validating docker creds from l0-setup isn't a good idea when you consider anyone can be using any custom auth scheme and/or private docker repos

**Comment by diemonster** [comment]
Addressed in https://github.com/quintilesims/layer0/pull/234
