### ISSUE TITLE
Investigate d.ims.io refactor

### ISSUE THREAD

**Issue by tribaljack** [quintilesims/layer0#258]
Currently d.ims.io is being labled as a $800/month "wastage" behind 4 instances, largely from idle CPU.  We want to address the service to make it more reliable, behave better with Auth0, and have better scalability/reliability.  So this is to investigate how to improve it, come up with a plan.

Acceptable outcome:
* plan forward work needed, and estimated operational cost 
* plan forward work needed, and justification on the instance size is needed.

**Comment by sesh-kebab** [comment]
Briefly investigated using docker credential helper https://github.com/awslabs/amazon-ecr-credential-helper. But we do not want to add an additional dependency at this stage. Additionally this line of investigation is somewhat outside of the scope of reducing the cost of d.ims.io.

**Comment by diemonster** [comment]
Closing for https://github.com/quintilesims/layer0/issues/269
