### ISSUE TITLE
if ECS re-schedules a task on a different instance, user-data.sh is not invoked

### ISSUE THREAD

**Issue by tribaljack** [quintilesims/layer0#26]
From Andy: 
repro is kinda out of my control on this one, but here's what happened:

1. new environment was created using user-data that attached a 1TB EBS vol.
2. service was started in this environment
3. service ran for a few days
4. ECS decided (why?) to re-schedule the task for this service on a new container instance.
5. that instance was started without running the user-data attached to the auto-scaling group

effect was that when the service re-started on the new instance, the EBS vol was not attached, so storage space was decimated.

**Comment by zpatrick** [comment]
It's likely the user data encountered an error during provisioning. Regardless, invoking user data is an aws mechanism outside of our control. Closing this issue since it isn't reproducible.
