### ISSUE TITLE
Refactor d.ims.io in Go

### ISSUE THREAD

**Issue by diemonster** [quintilesims/layer0#269]
### Expected behavior

Create a simple front-end web service that translates ECR's short-lived auth tokens to a long-term token for use with Layer0. 

### Refactor Goals

The current d.ims.io frontend is functional but inefficient and difficult to manage. As such, this refactor will be:

- a maintainable codebase written in Golang
- built on top of Layer0
- capable of debugging via service logs, etc

**Comment by zpatrick** [comment]
doesn't make sense to have this issue here. see https://github.com/quintilesims/d.ims.io
