### ISSUE TITLE
L0-Setup no longer automatically uploads tfstate file to s3

### ISSUE THREAD

**Issue by sesh-kebab** [quintilesims/layer0#271]
### Expected behavior
L0-setup transparently makes a copy of the state files in s3 when creating a new Layer0 instance.

### Actual behavior
As of v0.10.0 it no longer does this and requires explicitly running a `push` command.

### Steps to reproduce the behavior
Create a new layer0 environment using l0-setup. Confirm the s3 bucket corresponding to the new environment doesn't contain tfstate information.

Although the behavior has changed, the issue isn't stating that it is incorrect. Rather the issue is whether we should re-visit the decision to not automatically upload the tfstate files for a newly created l0 environment or not.

**Comment by zpatrick** [comment]
I think we should add this behavior as the default, and add a flag to make it configurable:
```
l0-setup apply --push=false INSTANCE
```
