### ISSUE TITLE
Revisit aws api layer

### ISSUE THREAD

**Issue by zpatrick** [quintilesims/layer0#274]
* [x] `controller` Package  -- For CRUD, filled letter means done, * means not yet, - means not needed.

**Note: Only Environment, LoadBalancer, and Service entities have the `Update` function!**

| Entity | Developer | Status | CRUD |
| - | - | - | - |
| Admin | nick | ✔️ | |
| Environment | tlake | ✔️ | CRUD |
| Service | tlake | ✔️ | CRUD |
| Task | Josh | ✔️  | CR-D |
| Deploy | Josh | ✔️  | CR-D |
| LB | Josh | ✔️  | CRUD |
| Job | - | - | - |
| Tag | Seshi | ✔️ |CR-D |

* [x] `provider/aws` Package

| Entity | Developer | Status | CRUD |
| - | - | - | - |
| Environment | - | ✔️ | CRUD |
| Service | tlake | ✔️ | CRUD |
| Task | Josh | ✔️ | CR-D |
| Deploy | Brandon/Josh | ✔️ | CR-D |
| LB | Zack | ✔️ | CRUD  |

* [x] `provider/aws` Unit Tests

| Entity | Developer | Status |
| - | - | - |
| Environment | - | - | 
| Service | tlake | ✔️ | 
| Task | Nick | ✔️ | 
| Deploy | Brandon | ✔️ | 
| LB | Josh | ✔️ | 

* [x] `client` Package

| Entity | Developer | Status |
| - | - | - |
| Environment | zack | ✔️ |
| Service | zack | ✔️ |
| Task | zack | ✔️ |
| Deploy | zack | ✔️ |
| LB | zack | ✔️ |

* [x] `command` Package

| Entity | Developer | Status |
| - | - | - |
| Environment | seshi | ✔️ |
| Service | tlake | ✔️ |
| Task | nick | ✔️ |
| Deploy | brandon | ✔️ |
| LB | josh | ✔️ |
| Resolver | zack | ✔️ |

* [x] `plugin/terraform` Package

| Entity | Developer | Status |
| - | - | - |
| Environment | zpatrick | qa |
| Service  | zpatrick | qa |
| Task   | zpatrick | qa |
| Deploy  | zpatrick | qa |
| LB    | zpatrick | qa  |

* [x] `job` Package
* [ ] `scaler` Package
   * [ ] #421 needs to be addressed
   * [ ] Does not scale horizontally
   * [ ] Should we be keeping ec2 instances around for at least an hour?
* [x] Job Janitor – Nick
* [x] Task Janitor – Nick
~* [ ] AWS Caching~ (removing this for now, to be tracked by https://github.com/quintilesims/layer0/issues/422)
~* [ ] Improve Tags~
* [x] Simplify error handling
* [x] Simplify logging
* [ ] Simplify config
* [x] Update Default Instance AMI
* [x] Documentation for `nowait` vs `wait`
* [x] Entity.Update(s) are not RESTful, they should exist at `PUT /entity/:id` instead of `PUT /entity`. We will need to create separate request/job models to accomplish this. 
* [x] CLI uses `entity read` vs `entity get` in different instances
* [x] Verify idempotent delete tests exist across all entities (@tlake)
* Update docs for terraform environment links
* Use T2.Medium or Small as default env size 

# Misc
* [x] Replace enum types with custom string types and constants
* [ ] API's deploy needs tags created on startup
* [ ] Windows AMIs are out of date 
* [ ] Ensure other regions' AMIs are correct (i.e. us-east-1)

**Comment by zpatrick** [comment]
Whiteboard issues:
* High # api calls
* Too much setup for tests
* Backend interface is too verbose
* redundant aws layer
* cached/manager layer
* handler, logic, ,backend layer has a redudancy
* working with tags is tedious
* ID management is pretty bad
* error handling - error model vs. real
* scheduler could use some TLC
* first class 'daemon' 
* use new `aws provider` in l0-setup 
* cleanup `common` package
* move `client` package to `common/client`

**Comment by diemonster** [comment]
Next steps:
- AWS Layer Refactor
- Backend interface skeleton
- First class "janitor" / daemon
- Cleanup common, logutils, `this`, move `client` to `common/client`, fix references

**Comment by tribaljack** [comment]
To avoid duplicate work, track breakdown using this below:

-Entity -Backend -Controller
-Environment -ZP -ZP
-Service  -   - 
-Task   -    -
-Deploy   -   -
-LB   -   -
-job   -   -

**Comment by diemonster** [comment]
As an additional measure, we should benchmark current, released API performance in some manner and compare after the refactor. This relates back to the discussion here https://github.com/quintilesims/layer0/pull/314#pullrequestreview-55359260

**Comment by diemonster** [comment]
Closing this for now as we're changing directions for the refactor.
