### ISSUE TITLE
l0-setup: `apply` fails after `init` due to bad var name

### ISSUE THREAD

**Issue by tlake** [quintilesims/layer0#278]
### Expected behavior

`$ l0-setup init [name]`
`$ l0-setup apply [name]`
☝️ works

### Actual behavior
```
$ l0-setup apply [name]
1 error(s) occurred:

* module root:
  module layer0.root:
  module api.layer0: 2 error(s) occurred:

* output 'dynamo_tag_table': unknown resource 'aws_dynamo_table.tags' referenced in variable aws_dynamo_table.tags.id
* output 'dynamo_job_table': unknown resource 'aws_dynamo_table.jobs' referenced in variable aws_dynamo_table.jobs.id
```

### Steps to reproduce the behavior

1. Clone current `develop` branch
2. `make build` CLI and API
3. `l0-setup init [name]`
4. `l0-setup apply [name]`

**Comment by zpatrick** [comment]
fixed by https://github.com/quintilesims/layer0/commit/a0f6464a68e53c55690f327dc021689460573b3c
