### ISSUE TITLE
Create a System Test for using same environment name 

### ISSUE THREAD

**Issue by diemonster** [quintilesims/layer0#335]
We're seeing some issues with Layer0 in a CI pipeline where a deleted environment (via `terraform destroy`) isn't clearing all of its former data in S3. This is causing `terraform destroy`s to return with a non-zero exit code on a same-named environment created via CI.

We should create a system test to debug this behavior and see what the next steps for fixing it may be.

### Expected behavior
Same-named environments destroyed via `terraform destroy` should return with a zero exit code

### Steps to reproduce the behavior

See above re: system tests.

**Comment by zpatrick** [comment]
Environments don't have any S3 resources, so I'm not sure what this is referencing?

**Comment by diemonster** [comment]
Closing this as it appears to be configuration-related and not a Layer0 bug.
