### ISSUE TITLE
Sporadic "Service XXX does not exist" error when creating service in Terraform provider

### ISSUE THREAD

**Issue by zpatrick** [quintilesims/layer0#339]
### Behavior
Creating a new Service using the Terraform provider will sometimes error with the message `Service XXX does not exist` even when it was actually created successfully. Subsequent `terraform apply` calls finish without errors. 

This error likely happens during the [`waitForDeploymentWithContext()`](https://github.com/quintilesims/layer0/blob/develop/plugins/terraform/resource_layer0_service.go#L71) call. This may be an "eventual consistency" error with AWS. 

### Steps to reproduce the behavior
This is sporadic behavior, but has happened when creating multiple services (3) at the same time via the Terraform provider. 

Layer0 Version: `10.0.3`

**Comment by tribaljack** [comment]
Closing as fixed.  If this happens again, open new ticket.
