### ISSUE TITLE
Investigate adding ECS API logs to Layer0 `logs` cmds

### ISSUE THREAD

**Issue by diemonster** [quintilesims/layer0#371]
Currently, we're gathering logs for a task's underlying container, but we also need to figure out if/how we can implement gathering additional log data from the ECS API itself, and whether those logs should be included within service logs or task logs or some other command: http://docs.aws.amazon.com/AmazonECS/latest/developerguide/logging-using-cloudtrail.html.

It appears as if ECS API logs will require us to sort data in CloudTrail and correlate that to a task or service by userIdentity to make them useful.

Alternatively, we could decide to forgo this work and try to figure out a way to dump the log data to Splunk.

**Comment by diemonster** [comment]
Appears as thought Splunk does integrate directly w CloudTrail, although they apparently prefer S3? https://docs.splunk.com/Documentation/AddOns/released/AWS/CloudTrail

Splunk also works for CloudWatch:
https://www.splunk.com/blog/2017/02/03/how-to-easily-stream-aws-cloudwatch-logs-to-splunk.html

**Comment by zpatrick** [comment]
CloudTail seems to be a dead end, as it only records api calls and not the associated metadata we would like to relay to our users. 

However, I did find that the metadata we would like to see is actually available via the `DescribeTasks` api call. Currently, this is stored in the `models.Task.Containers.Meta` field. I think we just need to add this lookup into `ServiceProvider.Read` and in the `models.Service` object.

**Comment by diemonster** [comment]
Duplicate of https://github.com/quintilesims/layer0/issues/573
