### ISSUE TITLE
Documentation bug: update terraform plugin installation instructions

### ISSUE THREAD

**Issue by andycmaj** [quintilesims/layer0#385]
### Expected behavior

copying `terraform-plugin-layer0` to `$(which terraform)`'s directory should make plugin available to tf version 0.10.7

### Actual behavior

copying the provider alongside the tf binary doesn't allow discoverability of the plugin.

### Steps to reproduce the behavior

```bash
$ cp /Workspace/ims/layer0_v0.10.3_darwin/terraform-provider-layer0 /usr/local/bin/
$ tf init
...

Provider "layer0" not available for installation.

A provider named "layer0" could not be found in the official repository.
...
```
fix it by copying to `.terraform.d/plugins` instead.

```bash
$ cp /Workspace/ims/layer0_v0.10.3_darwin/terraform-provider-layer0 ~/.terraform.d/plugins
$ tf init
...
Terraform has been successfully initialized!
```

new terraform plugin installation guidance: https://www.terraform.io/docs/configuration/providers.html#third-party-plugins

l0 version v0.10.3
Terraform v0.10.7

**Comment by tribaljack** [comment]
Re-validate in v0.11.0 after our API refactor and updated terraform plugin docs.

**Comment by diemonster** [comment]
No longer applicable as part of `api-refactor`
