### ISSUE TITLE
Default listener/default health check is created when creating a load balancer

### ISSUE THREAD

**Issue by jparsons04** [quintilesims/layer0#412]
### Expected behavior
Should a default port/default health check be created by default or should a request be required to provide a health check and at least one port?

### Actual behavior
When creating load balancers, if no ports are specified in the request, a default listener is created (TCP port 80 -> TCP port 80) and a health check is created also on TCP:80.

**Comment by jparsons04** [comment]
Spawned from this comment: https://github.com/quintilesims/layer0/pull/410#discussion_r148648378

**Comment by tribaljack** [comment]
Should have consolidated single place of entry for defaults for v0.11.0; behavior can change after.

**Comment by diemonster** [comment]
Closing, the behavior called out is/was intended.
