### ISSUE TITLE
cli/command package needs to use default model values defined in api/provider/aws/defaults.go rather than hard coded values

### ISSUE THREAD

**Issue by jparsons04** [quintilesims/layer0#413]
### Expected behavior
Given that we are defining default model values in `api/provider/aws/defaults.go`, we should make changes to cli/command package to use the constants/variables in the defaults file.

### Actual behavior
Default values for cli flags in the cli/command package are hard coded.

**Comment by jparsons04** [comment]
Spawned from this comment: https://github.com/quintilesims/layer0/pull/410#discussion_r148648745

**Comment by diemonster** [comment]
No longer applicable
