### ISSUE TITLE
Configure aws-sdk-go error retry logic

### ISSUE THREAD

**Issue by diemonster** [quintilesims/layer0#423]
The aws-sdk-go has exponential backoff and other retry logic params that are configurable for a given API client. This issue should track what options are relevant for Layer0 and the work done to implement those configurations.

http://docs.aws.amazon.com/general/latest/gr/api-retries.html

**Comment by jparsons04** [comment]
On initial inspection, it looks like we need to leverage [Config.Retryer](https://github.com/quintilesims/layer0/blob/develop/vendor/github.com/aws/aws-sdk-go/aws/config.go#L108) which is a `RequestRetryer` which is an alias for a type that implements the (request.Retryer interface)[https://github.com/quintilesims/layer0/blob/develop/vendor/github.com/aws/aws-sdk-go/aws/request/retryer.go#L13].

This interface has a method `RetryRules`. If you look at (DefaultRetryer's logic for RetryRules)[https://github.com/aws/aws-sdk-go/blob/master/aws/client/default_retryer.go#L37] there is a model we can use to customize our throttle handling logic.

**Comment by jparsons04** [comment]
The focus of setting this up could probably be done in `api/main.go` where we set up the client via `client := awsclient.NewClient(awsConfig)

**Comment by jparsons04** [comment]
Feature branch that adds new flags/new envvars has been merged into `api-refactor`
