### ISSUE TITLE
Automated Smoketests

### ISSUE THREAD

**Issue by diemonster** [quintilesims/layer0#43]
Smoketests should be automated and run when attempting to merge to `master`. This requires the following tasks as part of that automation:

- a Layer0 instance created by `l0-setup apply`
- smoketests triggered against the Layer0 instance
- Layer0 instance destroyed by `l0-setup destroy`

**Comment by diemonster** [comment]
@zpatrick if we are trying to display best practices around 12-factor apps, CI, and Layer0, I think we should allow `l0-setup` to take env vars as initial configuration (for the Layer0 instance name and id/secret key vals). How do you feel about this?

**Comment by zpatrick** [comment]
yep, this already exists using terraform variables: https://www.terraform.io/docs/configuration/environment-variables.html - e.g. `TF_VAR_access_key`. This doesn't exist for the instance name, but i think we don't need to add that in since we can pass that into the `l0-setup` command

**Comment by diemonster** [comment]
@zpatrick awesome, ok. thanks!

**Comment by diemonster** [comment]
Bug update: automation works when run interactively via shell commands. When run strictly via `make`, things get more complicated. 

Each line in a Makefile spawns its own subshell, so it's very difficult to pass environment variables set via a subshell to other subshells. This makes using `l0` difficult, as it is only configurable by environment variables, and the environment variables obtained by `l0-setup endpoint` are very temporary in this context.

In order to avoid hackery, docker-in-docker weirdness, and/or unmaintainable Makefiles, I think we should enable an optional config file for `l0`. This would get around the environment variable issue and would put `l0` more in line w other CLI tools similar to it, like `aws`, `docker`, `docker-machine`, and `heroku`. 

Thoughts?
