### ISSUE TITLE
Scaler: Environment scaled to 0 is not respected

### ISSUE THREAD

**Issue by tlake** [quintilesims/layer0#450]
### Expected behavior
When an environment is manually scaled down to 0 and has a task definition looking to place a service upon it, the scale should stay at 0.

### Actual behavior
When an environment is manually scaled down to 0 and has a task definition looking to place a service upon it, eventually something causes the max scale to increase.

### Steps to reproduce the behavior
- Manually scale an environment to 0
- Create a service that wants to place at least one thing into the environment
- Let the API sit and do its thing for a while, and monitor the scale with the dev version of the `CLI`

The most basic guestbook app in from `guides/walkthrough-1` is a good candidate for creating this scenario. Deploy it as usual, then scale the environment to `0:0:0`.

To avoid needing to wait for the API to run the scaler every hour, change `scalerDaemon.RunEvery(time.Hour)` in `layer0/api/main.go` to `scalerDaemon.RunEvery(time.Second * 10)` or something similar.

Terminal 1:
```
$ cd layer0/api && go run main.go -debug
```

Terminal 2:
```
$ cd layer0/cli && go run main.go environment set-scale ENVNAME --min-scale 0 --max-scale 0 && while true ; do date ; go run main.go environment get ENVNAME ; sleep 10 ; done
```

**Comment by zpatrick** [comment]
@tlake: are you sure you don't have a running api in aws that does this?

**Comment by tlake** [comment]
@zpatrick I had not even considered such a scenario, so I made sure the API environment was scaled down to 0 and let the local API spin for like, an hour, and everything seems to be functioning properly. Great catch!
