### ISSUE TITLE
Investigate ECS & Fargate for v0.11

### ISSUE THREAD

**Issue by diemonster** [quintilesims/layer0#467]
Let's keep our findings and discussion on Fargate tied to this issue. For now, we'll start with an introductory look into the service.

Brief introduction on AWS' Fargate:
https://aws.amazon.com/blogs/aws/aws-fargate/

Further networking implications for Layer0 to use Fargate:
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-networking.html

NOTE: Fargate is only supported in us-east-1 for the time being, although support for it has been added to `aws-sdk-go` in the ECS API.

**Comment by diemonster** [comment]
A critical open question is if we could/should convert "production" services to Fargate (i.e. Splunk). It seems unlikely that allowing AWS to fully manage the infrastructure would work for those types of 'static' services as we are too reliant on instance-level primitives, which Fargate wouldn't expose to us. 

However we chose to answer this question will have some big implications on what code we can rip out. I don't think our static services gain much, if anything, from the scaler, etc. But enabling their use and bootstrapping requires us to still maintain a lot of infrastructure management in our code.

**Comment by jparsons04** [comment]
The method (`SetLaunchType`) for the type `CreateServiceInput` is not present in our version of the SDK. Method: https://docs.aws.amazon.com/sdk-for-go/api/service/ecs/#CreateServiceInput.SetLaunchType

We are going to need to update the SDK version in our vendor tree to ensure that we have this method.

**Comment by tribaljack** [comment]
Believe investigation of fargate is sufficiently done.  ready for v0.11.0 removal of scaler...
