### ISSUE TITLE
Implement Static and Dynamic Environments

### ISSUE THREAD

**Issue by zpatrick** [quintilesims/layer0#498]
### common/models
  * Remove/replace Environment model's MinScale, CurrentScale, MaxScale fields. 
  * Add EnvironmentType field
```go
type Environment struct {
    ...
    CurrentScale    int
    DesiredScale    int
    EnvironmentType string
    ...
}
```
* Remove/Replace scale field in CreateEnvironmentRequest, add EnvironmentType
```go
type CreateEnvironmentRequest struct {
    ...
    Scale           int
    EnvironmentType string
}
```
* Update CreateEnvironmentRequest.Validate() to make sure they didn't specify a Scale & dynamic EnvironmentType
* Update `EnvironmentEnvironmentRequest` to take `Scale int` as the only param. 

### cli/command
* `l0 environment create` should take `--scale` flag
  * If `--scale` is specified, then it is a static environment
  * If `--scale` is not specified, then it is a dynamic environment
* replace `setmincount` and `setmaxcount` with `l0 environment scale NAME SCALE`

### cli/printer
* Show `SCALE` and `TYPE` when printing environments
```
l0 environment get foo*
ID       ...   SCALE   TYPE
foo123   ...   3/3     static
foo457   ...   -       dynamic
```

### api/providers/aws
* EnvironmentCreate() should add a tag for `environment_type`. This is either `static` or `dynamic`. 
* We should probably add a const in this package for the two environment types:
```go
const (
    EnvironmentTypeStatic  = "static"
    EnvironmentTypeDynamic = "dynamic"
)
```
* EnvironmentCreate() and EnvironmentDelete() should only Create/Delete LaunchConfigs and ASGs if they are static environments. 
* INVESTIGATION: Does fargate work with Windows? 
* EnvironmentRead() on static environments should populate DesiredScale and CurrentScale
  * DesiredScale should be taken from the [ASG's DesiredCapacity](https://github.com/aws/aws-sdk-go/blob/master/service/autoscaling/api.go#L9206).
  * CurrentScale should be taken from the [Cluster's RegisteredContainerInstancesCount](https://github.com/aws/aws-sdk-go/blob/master/service/ecs/api.go#L3837)
* EnvironmentUpdate() should error on dynamic environments, set the Min, Desired & Max Capacity for the environment's ASG on static environments.

### plugins/terraform
* Add `environment_type` as a field for the environment resource
* Make sure to read the new field(s) on the environment models for both the environment resource and data source.

**Comment by diemonster** [comment]
Re: Fargate on Windows: it does not work yet, just a feature request at this point. All windows containers should be considered "static" environments.
