### ISSUE TITLE
Download link via main docs.xfra.ims.io page gives 404 

### ISSUE THREAD

**Issue by diemonster** [quintilesims/layer0#50]
The link resolves to: `https://codeload.github.com/quintilesims/layer0/zip/v0.8.4`

**Comment by tlake** [comment]
What's the intended result of this link? I know that on the homepage there are three different download links, depending on OS. What's this link supposed to yield?

**Comment by zpatrick** [comment]
I think it should link to [#download](#) or [http://docs.xfra.ims.io/#download]()
