### ISSUE TITLE
Remove COUNT field from CLI's Task 'get'; replace with task.Status

### ISSUE THREAD

**Issue by diemonster** [quintilesims/layer0#508]
Our current display on the CLI from `task get` looks something like:

```
l0 task get pulltest
TASK ID       TASK NAME  ENVIRONMENT  DEPLOY     COUNT
pulltes8c55e  pulltest   PullTest     pulltet:1  0/1
pulltesa62c3  pulltest   PullTest     pulltet:2  0/1
```

`COUNT` is no longer a relevant field for tasks, so it should be removed. Instead, let's replace this field with `task.Status` data within a column name of STATUS (?) for quicker debugging.

**Comment by zpatrick** [comment]
this has been done in the `api-refactor` branch
