### ISSUE TITLE
Add full documentation for Dynamic and Static Environments 

### ISSUE THREAD

**Issue by diemonster** [quintilesims/layer0#537]
Our official docs need a full explanation of pros/cons of `static` versus `dynamic` environments. This discussion should at the minimum detail the following:

* Automatic scaling versus no scaling behavior 
* Amazon ECR use for private repos using dynamic envs
* `awsvpc` networking mode as default for Dynamic envs and what that means
* caveats for edge cases in dynamic envs (i.e. you don't have direct access to the Docker bus)

**Comment by sesh-kebab** [comment]
We should also include what ever our recommendation (be it ECR credential helper or something else) for dealing with private repo authentication when using dynamic environments.

**Comment by tribaljack** [comment]
We're doing stateful vs stateless in task definition and at service level, not in environment level.  closing as won't do.
