### ISSUE TITLE
Stateful vs Stateless Application Workflow

### ISSUE THREAD

**Issue by diemonster** [quintilesims/layer0#554]
Currently, we've defined the difference between EC2 vs Fargate launch types as `static` versus `dynamic`. We should adopt terminology that is focused less on the ability to scale and more on the application type, i.e. stateful versus stateless. As such, the first part of this task might be as simple as find/replace.

Secondly, we should make some intelligent decisions up front for the users of stateful applications. For instance, all stateful applications require statically mapped data volumes. Many stateful applications require placement constraints (see: Splunk). If we can make some of these choices for users in advance, it will make the stateful workflow far more useful.

**Comment by tribaljack** [comment]
Work on this is being tracked by #500.  Closing as dupe
