### ISSUE TITLE
If Layer0 fails during resource creation then Terraform cannot recover on a second run

### ISSUE THREAD

**Issue by Cryowatt** [quintilesims/layer0#558]
We had a scenario where L0 failed to create an environment, resulting in the following Terraform error message:
```
1 error(s) occurred:

* layer0_environment.environment: 1 error(s) occurred:

* layer0_environment.environment: EOF
```

Terraform was run again, but ended with this different error:
```
1 error(s) occurred:

* layer0_environment.environment: 1 error(s) occurred:

* layer0_environment.environment: ServerError (code=6) Environment with name 'foo_environment_52ce64c' already exists
```

Terraform destroy cannot recover from this error, so the only choice is to manually remove resources from AWS and recreate the environment.

Preferably L0 should be able to gracefully recover from these sorts of errors.

### Steps to reproduce the behavior
Unfortunately, this is usually caused by random unreproducible errors so I have no repro steps. Injecting faults into the resource creation workflow might reproduce the issue.

**Comment by zpatrick** [comment]
@Cryowatt do you have access to logs around the time of that failure (`l0 service logs --start xx --end yy api`) ? That `EOF` error usually means the api hit some unhandled exception.

**Comment by diemonster** [comment]
Closing because we cannot repro
