### ISSUE TITLE
Configure Cross-Zone Load Balancing for the Classic Load Balancer

### ISSUE THREAD

**Issue by qayshp** [quintilesims/layer0#642]
### Expected behavior
Either hard-code Cross-Zone Load Balancing to enabled, or allow it to be specified.

### Actual behavior
Defaults to disabled as that is the AWS API default.
> the default for cross-zone load balancing depends on how you create the load balancer. With the API or CLI, cross-zone load balancing is disabled by default. With the AWS Management Console, the option to enable cross-zone load balancing is selected by default. After you create a Classic Load Balancer, you can enable or disable cross-zone load balancing at any time
https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-disable-crosszone-lb.html

**Comment by tlake** [comment]
- [ ] Layer0 CLI
- [ ] Layer0 API
- [ ] Terraform Plugin
- [ ] Tests
- [ ] Docs
