### ISSUE TITLE
Bump L0 API instance to t3.small

### ISSUE THREAD

**Issue by alqvia** [quintilesims/layer0#652]
### Expected behavior
Deploying to `us-west-2` succeeds with all AZs.

### Actual behavior
Deploying L0 instance to `us-west-2` gives the following error message:

```
Description:Description
Launching a new EC2 instance. 
Status Reason: Your requested instance type (t2.small) is not supported in your requested Availability Zone (us-west-2d). 
Please retry your request by not specifying an Availability Zone or choosing us-west-2a, us-west-2b, us-west-2c. Launching EC2 instance failed.
```

Currently, the EC2 `instance_type` defined in `aws_launch_configuration` (environment.tf) is set to `t2.small`, which is no longer supported by the `us-west-2d` AZ. `t2.small` is an older type that should be replaced with `t3.small`.

### Steps to reproduce the behavior
Deploy L0 to `us-west-2`

**Comment by diemonster** [comment]
@alqvia we suspect this is a terraform-specific bug. If you run `l0-setup apply` twice, the second time running will apply another change including the `2d` subnets into the VPC configuration. 

If you follow the suggestion above, do you still get the same error message?

for reference, a similar error: https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/issues/68

**Comment by alqvia** [comment]
I'll give it a try

**Comment by alqvia** [comment]
Okay, so this seemed to work on the first `l0-setup apply`...

**Comment by alqvia** [comment]
Re-running `init` and `apply` worked.
