### ISSUE TITLE
Allow placementConstraints to be added in the task definition file

### ISSUE THREAD

**Issue by sesh-kebab** [quintilesims/layer0#83]
Adding this would open up a whole world of task placement strategies. Although I realize it may not really fit with Layer0, it would just be exposing functionality that already exists in AWS ECS and provide additional flexibility for outlying use cases.

http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_TaskDefinitionPlacementConstraint.html

**Comment by diemonster** [comment]
@sesh-kebab good call, this is a nice feature to have. We will definitely prioritize this, should be an easy addition.
