### ISSUE TITLE
When no tag is specified for a 'deploy', assume 'latest'

### ISSUE THREAD

**Issue by diemonster** [quintilesims/layer0#87]
As seen in https://github.com/quintilesims/layer0/issues/72, it is currently necessary to target an explicit tag (i.e. `latest` ) when referencing a `deploy`. 

When a tag is omitted, the CLI should default to `latest`. This is the default behavior of the `docker` CLI when working with Docker images & tags, and we should try to remain in parity with that UX.

**Comment by zpatrick** [comment]
One thing to note is that this conflicts with the resolving behavior of other entities:
`l0 <entity> get target` - will return 1 entity if `target` exactly matches an entity id or 1 to many entities if `target` matches an entity name.
`l0 <entity> get target*` - will return 1 to many entities if `target` matches a prefix of an entity id or name. 

If we always append `:latest` to a deploy, the `l0 deploy get target` and `l0 deploy get target*` will only ever return up to 1 entity.
