### ISSUE TITLE
`l0 destroy` leaving old tags in tag database? [possible bug]

### ISSUE THREAD

**Issue by tlake** [quintilesims/layer0#93]
In trying to test out some behavior for healthchecks with the Layer0 Terraform provider, I ran into an issue. Not sure if this is a proper bug, but Brandon and I thought it would be a good idea to at least document the error and its resolution for posterity.

## The Lead-In
- An old set of resources had been created using the Layer0 Terraform provider:
    - An environment named `health-env`
    - A load balancer named `health-lb`
    - A deploy and a service following the same naming patterns
- These resources were able to be viewed and edited with the Layer0 CLI
- These resources had been destroyed with the Layer0 CLI

## The Problem
I then made some updates to the provider plugin, rebuilt it, and ran `terraform plan` with a fully-configured `layer0.tf` file:
```
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.

data.template_file.guestbook: Refreshing state...

The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed. Cyan entries are data sources to be read.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

+ layer0_deploy.health-dep
    content: "{\n    \"AWSEBDockerrunVersion\": 2,\n    \"containerDefinitions\": [\n        {\n            \"name\": \"l0-demo-guestbook\",\n            \"image\": \"quintilesims/l0-guestbook\",\n            \"essential\": true,\n            \"memory\": 128,\n            \"portMappings\": [\n                {\n                    \"hostPort\": 80,\n                    \"containerPort\": 80\n                }\n            ]\n        }\n    ]\n}\n"
    name:    "health-dep"

+ layer0_environment.health-env
    cluster_count:     "<computed>"
    name:              "health-env"
    security_group_id: "<computed>"
    size:              "m3.medium"

+ layer0_load_balancer.health-lb
    environment:                    "${layer0_environment.health-env.id}"
    health_check.#:                 "<computed>"
    name:                           "health-lb"
    port.#:                         "1"
    port.2027667003.certificate:    ""
    port.2027667003.container_port: "80"
    port.2027667003.host_port:      "80"
    port.2027667003.protocol:       "http"
    url:                            "<computed>"

+ layer0_service.health-svc
    deploy:        "${layer0_deploy.health-dep.id}"
    environment:   "${layer0_environment.health-env.id}"
    load_balancer: "${layer0_load_balancer.health-lb.id}"
    name:          "health-svc"
    scale:         "1"


Plan: 4 to add, 0 to change, 0 to destroy.
```

The plan worked fine. Running `terraform apply` resulted in an error:
```
$ terraform apply
data.template_file.guestbook: Refreshing state...
layer0_environment.health-env: Creating...
  cluster_count:     "" => "<computed>"
  name:              "" => "health-env"
  security_group_id: "" => "<computed>"
  size:              "" => "m3.medium"
layer0_deploy.health-dep: Creating...
  content: "" => "{\n    \"AWSEBDockerrunVersion\": 2,\n    \"containerDefinitions\": [\n        {\n            \"name\": \"l0-demo-guestbook\",\n            \"image\": \"quintilesims/l0-guestbook\",\n            \"essential\": true,\n            \"memory\": 128,\n            \"portMappings\": [\n                {\n                    \"hostPort\": 80,\n                    \"containerPort\": 80\n                }\n            ]\n        }\n    ]\n}\n"
  name:    "" => "health-dep"
layer0_deploy.health-dep: Creation complete
Error applying plan:

1 error(s) occurred:

* layer0_environment.health-env: Environment with name 'health-env' already exists

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

## Failed Solution Attempts
Running `l0 environment list` showed only the API existing:
```
$ l0 environment list
ENVIRONMENT ID  ENVIRONMENT NAME
api             api
```

I then tried to manually destroy or taint the terraform resource, with no success:
```
$ terraform destroy --target=layer0_environment.health-env
Do you really want to destroy?
  Terraform will delete the following infrastructure:
  	layer0_environment.health-env
  There is no undo. Only 'yes' will be accepted to confirm

  Enter a value: yes


Destroy complete! Resources: 0 destroyed.
```

```
$ terraform taint layer0_environment.health-env
The module root has no resources. There is nothing to taint.
```

## Successful Solution
I connected a browser to `LAYER0_API_ENDPOINT/apidocs` and made a blank `TAGS GET` request (to get the username and password, run the following)
```
echo `echo $LAYER0_AUTH_TOKEN | base64 --decode`
```
The `GET` request printed out all the tags found in the database, and I scrolled through until I found the offending `health-env` entry:
```
{
    "entity_id": "healthe2a9f1",
    "entity_type": "environment",
    "tags": [
      {
        "entity_id": "healthe2a9f1",
        "entity_type": "environment",
        "key": "name",
        "value": "health-env"
      }
    ]
  },
```
I took just the tag JSON...
```
      {
        "entity_id": "healthe2a9f1",
        "entity_type": "environment",
        "key": "name",
        "value": "health-env"
      }
```
...and pasted it into the body of a `TAGS DELETE` request. I was then able to successfully run `terraform apply`.

**Comment by zpatrick** [comment]
There's a lot of info here - going to try and suss out the extras:

* Terraform is definitely **not** the culprit here. In everything you described (create with terraform, delete with layer0 cli, etc.) terraform is behaving exactly as expected.
* What you are describing is simply a failed `l0 environment delete` (since you said you deleted the environment with the layer0 cli). So the question is, did the environment delete job report that it had a failure? If not, we have an issue. If it did, we should check the logs to find what the error was.

**Comment by tlake** [comment]
All fair points - I'll update the issue.

I believe that this is the relevant log: https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logEventViewer:group=l0-tlakedev;stream=l0/l0-job/34e756b5-b8e4-42d2-bb66-e8fcb6a7d9b6

Looks like it timed out while trying to delete the security group.

**Comment by zpatrick** [comment]
security group timeouts typically fail when there is a dependent aws resource that isn't getting deleted (usually a load balancer, ec2 instance, etc.). Since the job properly reported the error, this seems to be the expected behavior.
